import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTextField;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.awt.Color;

public class MenuBarGUI extends JFrame { 
    
    private JMenuBar menuBar = new JMenuBar();
    private JMenu fileMenu = new JMenu("Options");

    private JMenuItem dateButton; //menu button for printing time into the textbox
    private JTextField textField;//field for printing date and time and to be saved to log.txt
    private JMenuItem saveButton;  //menu button for saving text to log.txt
    private JMenuItem changeBackground; //menu button to change background
    private JMenuItem closeProgram; //menu button to close
    private int red; //three int vars for storing rgb values generated by method
    private int blue;
    private int green;
    
    public static final String FILENAME = "log.txt"; //setting filename here to make it easily changeable or even user enterable is needed

    public void save() { //save method to save the text field to a log file
        try (PrintWriter writer = new PrintWriter(new FileWriter(FILENAME))) { 
            writer.println(textField.getText());
        } catch (IOException e) {
            System.out.println("\nError saving file: " + e.getMessage());
        }
    }

    
    MenuBarGUI() {      // Used to specify GUI component layout
        GridBagConstraints layoutConst = null;

        // Set frame's title
        setTitle("GUI BANK INC.");
        dateButton = new JMenuItem("Display Date"); 
        saveButton = new JMenuItem("Save Text");
        changeBackground = new JMenuItem("Change BackGround"); 
        closeProgram = new JMenuItem("Exit");
    
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy"); //setting up a simple date format

        dateButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                textField.setText(sdf.format(new Date())); //fills text field with date
            }
        });

        saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                save(); //runs the save method
            }
        });

        changeBackground.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                getRandomRBG(); //runs the method 
                getContentPane().setBackground(new Color(red, green, blue)); //sets background based on values from getRandomRBG method
            }
        });

        closeProgram.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.exit(0); //closes window
            }
        });

        // Create withdrawl amount field
        textField = new JFormattedTextField();
        textField.setText(""); //field for printing date and time and to be saved to log.txt
        textField.setEditable(true);
        textField.setColumns(15);

        // Use a GridBagLayout
        setLayout(new GridBagLayout());
       
        layoutConst = new GridBagConstraints();
        layoutConst.insets = new Insets(10, 1, 10, 10);
        layoutConst.gridx = 1;
        layoutConst.gridy = 0;
        add(textField, layoutConst);
        
        // Assemble the components
        fileMenu.add(dateButton);
        fileMenu.add(saveButton);
        fileMenu.add(changeBackground);
        fileMenu.add(closeProgram);

        menuBar.add(fileMenu);
        
        // Attach the menu bar to the frame
        setJMenuBar(menuBar);
        getRandomRBG(); //inital run of the method to pull random rgb values
        getContentPane().setBackground(new Color(red, green, blue)); //setting first background color
   }
    
   public void getRandomRBG() { //method to randomly pull the three rgb values
            Random rand = new Random();
            red = rand.nextInt(255);
            green = rand.nextInt(255);
            blue = rand.nextInt(255);
        
        }

    public static void main(String[] args) {
        MenuBarGUI myFrame = new MenuBarGUI();
        myFrame.setSize(400, 300);
        myFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        myFrame.setVisible(true);
    }

}
